# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from ..._models import BaseModel
from ..shared.option import Option

__all__ = ["FieldTypeDefinition"]


class FieldTypeDefinition(BaseModel):
    external_options: bool = FieldInfo(alias="externalOptions")

    name: str

    options: List[Option]

    type: Literal[
        "bool",
        "currency_number",
        "date",
        "datetime",
        "enumeration",
        "json",
        "number",
        "object_coordinates",
        "phone_number",
        "string",
    ]

    description: Optional[str] = None

    external_options_reference_type: Optional[str] = FieldInfo(alias="externalOptionsReferenceType", default=None)

    field_type: Optional[
        Literal[
            "booleancheckbox",
            "calculation_equation",
            "calculation_read_time",
            "calculation_rollup",
            "calculation_score",
            "checkbox",
            "date",
            "file",
            "html",
            "number",
            "phonenumber",
            "radio",
            "select",
            "text",
            "textarea",
            "unknown",
        ]
    ] = FieldInfo(alias="fieldType", default=None)

    help_text: Optional[str] = FieldInfo(alias="helpText", default=None)

    label: Optional[str] = None

    options_url: Optional[str] = FieldInfo(alias="optionsUrl", default=None)

    referenced_object_type: Optional[
        Literal[
            "ABANDONED_CART",
            "ACCEPTANCE_TEST",
            "AD",
            "AD_ACCOUNT",
            "AD_CAMPAIGN",
            "AD_GROUP",
            "AI_FORECAST",
            "ALL_PAGES",
            "APPROVAL",
            "APPROVAL_STEP",
            "ATTRIBUTION",
            "AUDIENCE",
            "AUTOMATION_JOURNEY",
            "AUTOMATION_PLATFORM_FLOW",
            "AUTOMATION_PLATFORM_FLOW_ACTION",
            "BET_ALERT",
            "BET_DELIVERABLE_SERVICE",
            "BLOG_LISTING_PAGE",
            "BLOG_POST",
            "CALL",
            "CAMPAIGN",
            "CAMPAIGN_BUDGET_ITEM",
            "CAMPAIGN_SPEND_ITEM",
            "CAMPAIGN_STEP",
            "CAMPAIGN_TEMPLATE",
            "CAMPAIGN_TEMPLATE_STEP",
            "CART",
            "CHATFLOW",
            "CLIP",
            "CMS_URL",
            "COMMERCE_PAYMENT",
            "COMMUNICATION",
            "COMPANY",
            "CONTACT",
            "CONTACT_CREATE_ATTRIBUTION",
            "CONTENT",
            "CONTENT_AUDIT",
            "CONTENT_AUDIT_PAGE",
            "CONVERSATION",
            "CONVERSATION_INBOX",
            "CONVERSATION_SESSION",
            "CRM_PIPELINES_DUMMY_TYPE",
            "CTA",
            "CTA_VARIANT",
            "DATA_PRIVACY_CONSENT",
            "DATA_SYNC_STATE",
            "DEAL",
            "DEAL_CREATE_ATTRIBUTION",
            "DEAL_REGISTRATION",
            "DEAL_SPLIT",
            "DISCOUNT",
            "DISCOUNT_CODE",
            "DISCOUNT_TEMPLATE",
            "EMAIL",
            "ENGAGEMENT",
            "EXPORT",
            "EXTERNAL_WEB_URL",
            "FEE",
            "FEEDBACK_SUBMISSION",
            "FEEDBACK_SURVEY",
            "FILE_MANAGER_FILE",
            "FILE_MANAGER_FOLDER",
            "FOLDER",
            "FORECAST",
            "FORM",
            "FORM_SUBMISSION_INBOUNDDB",
            "GOAL_TARGET",
            "GOAL_TARGET_GROUP",
            "GOAL_TEMPLATE",
            "GSC_PROPERTY",
            "HUB",
            "IMPORT",
            "INVOICE",
            "KEYWORD",
            "KNOWLEDGE_ARTICLE",
            "LANDING_PAGE",
            "LEAD",
            "LINE_ITEM",
            "MARKETING_CALENDAR",
            "MARKETING_CAMPAIGN_UTM",
            "MARKETING_EMAIL",
            "MARKETING_EVENT",
            "MARKETING_EVENT_ATTENDANCE",
            "MARKETING_SMS",
            "MEDIA_BRIDGE",
            "MEETING_EVENT",
            "MIC",
            "NOTE",
            "OBJECT_LIST",
            "ORDER",
            "OWNER",
            "PARTNER_ACCOUNT",
            "PARTNER_CLIENT",
            "PARTNER_CLIENT_REVENUE",
            "PAYMENT_LINK",
            "PAYMENT_SCHEDULE",
            "PAYMENT_SCHEDULE_INSTALLMENT",
            "PERMISSIONS_TESTING",
            "PLAYBOOK",
            "PLAYBOOK_QUESTION",
            "PLAYBOOK_SUBMISSION",
            "PLAYBOOK_SUBMISSION_ANSWER",
            "PLAYLIST",
            "PLAYLIST_FOLDER",
            "PORTAL",
            "PORTAL_OBJECT_SYNC_MESSAGE",
            "POSTAL_MAIL",
            "PRIVACY_SCANNER_COOKIE",
            "PRODUCT",
            "PRODUCT_OR_FOLDER",
            "PROPERTY_INFO",
            "PUBLISHING_TASK",
            "QUARANTINED_SUBMISSION",
            "QUOTA",
            "QUOTE",
            "QUOTE_FIELD",
            "QUOTE_MODULE",
            "QUOTE_MODULE_FIELD",
            "QUOTE_TEMPLATE",
            "RESTORABLE_CRM_OBJECT",
            "ROSTER",
            "ROSTER_MEMBER",
            "SALES_DOCUMENT",
            "SALES_TASK",
            "SALES_WORKLOAD",
            "SALESFORCE_SYNC_ERROR",
            "SCHEDULING_PAGE",
            "SCHEMAS_BACKEND_TEST",
            "SCORE_CONFIGURATION",
            "SEQUENCE",
            "SEQUENCE_ENROLLMENT",
            "SEQUENCE_STEP",
            "SEQUENCE_STEP_ENROLLMENT",
            "SITE_PAGE",
            "SNIPPET",
            "SOCIAL_BROADCAST",
            "SOCIAL_CHANNEL",
            "SOCIAL_POST",
            "SOCIAL_PROFILE",
            "SOX_PROTECTED_DUMMY_TYPE",
            "SOX_PROTECTED_TEST_TYPE",
            "SUBMISSION_TAG",
            "SUBSCRIPTION",
            "TASK",
            "TASK_TEMPLATE",
            "TAX",
            "TEMPLATE",
            "TICKET",
            "UNKNOWN",
            "UNSUBSCRIBE",
            "USER",
            "VIEW",
            "VIEW_BLOCK",
            "WEB_INTERACTIVE",
        ]
    ] = FieldInfo(alias="referencedObjectType", default=None)
