# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from ..._models import BaseModel
from .import_row_core import ImportRowCore
from ..marketing.property_value import PropertyValue

__all__ = ["PublicImportError"]


class PublicImportError(BaseModel):
    id: str

    created_at: int = FieldInfo(alias="createdAt")

    error_type: Literal[
        "INCORRECT_NUMBER_OF_COLUMNS",
        "INVALID_OBJECT_ID",
        "INVALID_ASSOCIATION_IDENTIFIER",
        "NO_OBJECT_ID_FROM_ASSOCIATION_IDENTIFIER",
        "MULTIPLE_COMPANIES_WITH_THIS_DOMAIN",
        "PROPERTY_DEFINITION_NOT_FOUND",
        "PROPERTY_VALUE_NOT_FOUND",
        "COULD_NOT_FIND_OWNER",
        "MULTIPLE_OWNERS_FOUND",
        "COULD_NOT_FIND_BUSINESS_UNIT",
        "COULD_NOT_PARSE_NUMBER",
        "COULD_NOT_PARSE_DATE",
        "COULD_NOT_PARSE_TERM",
        "OUTSIDE_VALID_TIME_RANGE",
        "OUTSIDE_VALID_TERM_RANGE",
        "COULD_NOT_PARSE_ROW",
        "INVALID_ENUMERATION_OPTION",
        "AMBIGUOUS_ENUMERATION_OPTION",
        "FAILED_VALIDATION",
        "FAILED_TO_CREATE_ASSOCIATION",
        "ASSOCIATION_LIMIT_EXCEEDED",
        "FILE_NOT_FOUND",
        "INVALID_COLUMN_CONFIGURATION",
        "INVALID_FILE_TYPE",
        "INVALID_SPREADSHEET",
        "INVALID_SHEET_COUNT",
        "FAILED_TO_PROCESS_OBJECT_WITH_EMPTY_PROPERTY_VALUES",
        "UNKNOWN_BAD_REQUEST",
        "GDPR_BLACKLISTED_EMAIL",
        "DUPLICATE_ASSOCIATION_ID",
        "LIMIT_EXCEEDED",
        "PORTAL_WIDE_CUSTOM_OBJECT_LIMIT_EXCEEDED",
        "INVALID_ALTERNATE_ID",
        "INVALID_EMAIL",
        "SECONDARY_EMAIL_WRITE_FAILURE",
        "INVALID_DOMAIN",
        "DUPLICATE_ROW_CONTENT",
        "INVALID_NUMBER_SIZE",
        "UNKNOWN_ERROR",
        "FAILED_TO_OPT_OUT_CONTACT",
        "INVALID_REQUIRED_PROPERTY",
        "MISSING_REQUIRED_PROPERTY",
        "DUPLICATE_ALTERNATE_ID",
        "DUPLICATE_OBJECT_ID",
        "DUPLICATE_UNIQUE_PROPERTY_VALUE",
        "UNKNOWN_ASSOCIATION_RECORD_ID",
        "INVALID_RECORD_ID",
        "DUPLICATE_RECORD_ID",
        "INVALID_CUSTOM_PROPERTY_VALIDATION",
        "CREATE_ONLY_IMPORT",
        "UPDATE_ONLY_IMPORT",
        "COLUMN_TOO_LARGE",
        "ROW_DATA_TOO_LARGE",
        "MISSING_EVENT_TIMESTAMP",
        "INVALID_EVENT_TIMESTAMP",
        "INVALID_EVENT",
        "DUPLICATE_EVENT",
        "MISSING_EVENT_DEFINITION",
        "INVALID_ASSOCIATION_KEY",
        "ASSOCIATION_RECORD_NOT_FOUND",
        "MISSING_OBJECT_DEFINITION",
        "ASSOCIATION_LABEL_NOT_FOUND",
        "MANY_ERRORS_IN_ROW",
    ] = FieldInfo(alias="errorType")

    source_data: ImportRowCore = FieldInfo(alias="sourceData")

    error_message: Optional[str] = FieldInfo(alias="errorMessage", default=None)

    extra_context: Optional[str] = FieldInfo(alias="extraContext", default=None)

    invalid_property_value: Optional[PropertyValue] = FieldInfo(alias="invalidPropertyValue", default=None)
    """
    Represents a single custom property of a marketing event, storing its name,
    value, metadata (like source, timestamp, and sensitivity), and related audit
    information for tracking changes.
    """

    invalid_value: Optional[str] = FieldInfo(alias="invalidValue", default=None)

    invalid_value_to_display: Optional[str] = FieldInfo(alias="invalidValueToDisplay", default=None)

    known_column_number: Optional[int] = FieldInfo(alias="knownColumnNumber", default=None)

    object_type: Optional[
        Literal[
            "CONTACT",
            "COMPANY",
            "DEAL",
            "ENGAGEMENT",
            "TICKET",
            "OWNER",
            "PRODUCT",
            "LINE_ITEM",
            "BET_DELIVERABLE_SERVICE",
            "CONTENT",
            "CONVERSATION",
            "BET_ALERT",
            "PORTAL",
            "QUOTE",
            "FORM_SUBMISSION_INBOUNDDB",
            "QUOTA",
            "UNSUBSCRIBE",
            "COMMUNICATION",
            "FEEDBACK_SUBMISSION",
            "ATTRIBUTION",
            "SALESFORCE_SYNC_ERROR",
            "RESTORABLE_CRM_OBJECT",
            "HUB",
            "LANDING_PAGE",
            "PRODUCT_OR_FOLDER",
            "TASK",
            "FORM",
            "MARKETING_EMAIL",
            "AD_ACCOUNT",
            "AD_CAMPAIGN",
            "AD_GROUP",
            "AD",
            "KEYWORD",
            "CAMPAIGN",
            "SOCIAL_CHANNEL",
            "SOCIAL_POST",
            "SITE_PAGE",
            "BLOG_POST",
            "IMPORT",
            "EXPORT",
            "CTA",
            "TASK_TEMPLATE",
            "AUTOMATION_PLATFORM_FLOW",
            "OBJECT_LIST",
            "NOTE",
            "MEETING_EVENT",
            "CALL",
            "EMAIL",
            "PUBLISHING_TASK",
            "CONVERSATION_SESSION",
            "CONTACT_CREATE_ATTRIBUTION",
            "INVOICE",
            "MARKETING_EVENT",
            "CONVERSATION_INBOX",
            "CHATFLOW",
            "MEDIA_BRIDGE",
            "SEQUENCE",
            "SEQUENCE_STEP",
            "FORECAST",
            "SNIPPET",
            "TEMPLATE",
            "DEAL_CREATE_ATTRIBUTION",
            "QUOTE_TEMPLATE",
            "QUOTE_MODULE",
            "QUOTE_MODULE_FIELD",
            "QUOTE_FIELD",
            "SEQUENCE_ENROLLMENT",
            "SUBSCRIPTION",
            "ACCEPTANCE_TEST",
            "SOCIAL_BROADCAST",
            "DEAL_SPLIT",
            "DEAL_REGISTRATION",
            "GOAL_TARGET",
            "GOAL_TARGET_GROUP",
            "PORTAL_OBJECT_SYNC_MESSAGE",
            "FILE_MANAGER_FILE",
            "FILE_MANAGER_FOLDER",
            "SEQUENCE_STEP_ENROLLMENT",
            "APPROVAL",
            "APPROVAL_STEP",
            "CTA_VARIANT",
            "SALES_DOCUMENT",
            "DISCOUNT",
            "FEE",
            "TAX",
            "MARKETING_CALENDAR",
            "PERMISSIONS_TESTING",
            "PRIVACY_SCANNER_COOKIE",
            "DATA_SYNC_STATE",
            "WEB_INTERACTIVE",
            "PLAYBOOK",
            "FOLDER",
            "PLAYBOOK_QUESTION",
            "PLAYBOOK_SUBMISSION",
            "PLAYBOOK_SUBMISSION_ANSWER",
            "COMMERCE_PAYMENT",
            "GSC_PROPERTY",
            "SOX_PROTECTED_DUMMY_TYPE",
            "BLOG_LISTING_PAGE",
            "QUARANTINED_SUBMISSION",
            "PAYMENT_SCHEDULE",
            "PAYMENT_SCHEDULE_INSTALLMENT",
            "MARKETING_CAMPAIGN_UTM",
            "DISCOUNT_TEMPLATE",
            "DISCOUNT_CODE",
            "FEEDBACK_SURVEY",
            "CMS_URL",
            "SALES_TASK",
            "SALES_WORKLOAD",
            "USER",
            "POSTAL_MAIL",
            "SCHEMAS_BACKEND_TEST",
            "PAYMENT_LINK",
            "SUBMISSION_TAG",
            "CAMPAIGN_STEP",
            "SCHEDULING_PAGE",
            "SOX_PROTECTED_TEST_TYPE",
            "ORDER",
            "MARKETING_SMS",
            "PARTNER_ACCOUNT",
            "CAMPAIGN_TEMPLATE",
            "CAMPAIGN_TEMPLATE_STEP",
            "PLAYLIST",
            "CLIP",
            "CAMPAIGN_BUDGET_ITEM",
            "CAMPAIGN_SPEND_ITEM",
            "MIC",
            "CONTENT_AUDIT",
            "CONTENT_AUDIT_PAGE",
            "PLAYLIST_FOLDER",
            "LEAD",
            "ABANDONED_CART",
            "EXTERNAL_WEB_URL",
            "VIEW",
            "VIEW_BLOCK",
            "ROSTER",
            "CART",
            "AUTOMATION_PLATFORM_FLOW_ACTION",
            "SOCIAL_PROFILE",
            "PARTNER_CLIENT",
            "ROSTER_MEMBER",
            "MARKETING_EVENT_ATTENDANCE",
            "ALL_PAGES",
            "AI_FORECAST",
            "CRM_PIPELINES_DUMMY_TYPE",
            "KNOWLEDGE_ARTICLE",
            "PROPERTY_INFO",
            "DATA_PRIVACY_CONSENT",
            "GOAL_TEMPLATE",
            "SCORE_CONFIGURATION",
            "AUDIENCE",
            "PARTNER_CLIENT_REVENUE",
            "AUTOMATION_JOURNEY",
            "COMBO_EVENT_CONFIGURATION",
            "CRM_OBJECTS_DUMMY_TYPE",
            "CASE_STUDY",
            "SERVICE",
            "PODCAST_EPISODE",
            "PARTNER_SERVICE",
            "PROSPECTING_AGENT_CONTACT_ASSIGNMENT",
            "UNKNOWN",
        ]
    ] = FieldInfo(alias="objectType", default=None)

    object_type_id: Optional[str] = FieldInfo(alias="objectTypeId", default=None)
