# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .shared import (
    Filter as Filter,
    Option as Option,
    Paging as Paging,
    NextPage as NextPage,
    Property as Property,
    Condition as Condition,
    ErrorData as ErrorData,
    ErrorDetail as ErrorDetail,
    OptionInput as OptionInput,
    TaskLocator as TaskLocator,
    VersionUser as VersionUser,
    PreviousPage as PreviousPage,
    PropertyName as PropertyName,
    ForwardPaging as ForwardPaging,
    PropertyGroup as PropertyGroup,
    PropertyValue as PropertyValue,
    StandardError as StandardError,
    ActionResponse as ActionResponse,
    FilterResponse as FilterResponse,
    PropertyCreate as PropertyCreate,
    PublicObjectID as PublicObjectID,
    AssociationSpec as AssociationSpec,
    BatchInputString as BatchInputString,
    FilterCreateRequest as FilterCreateRequest,
    PropertyGroupCreate as PropertyGroupCreate,
    PropertyGroupUpdate as PropertyGroupUpdate,
    FilterCreateResponse as FilterCreateResponse,
    JournalFetchResponse as JournalFetchResponse,
    ObjectTypeDefinition as ObjectTypeDefinition,
    ActionOverrideRequest as ActionOverrideRequest,
    AssociationDefinition as AssociationDefinition,
    BatchInputPropertyName as BatchInputPropertyName,
    SnapshotStatusResponse as SnapshotStatusResponse,
    AutomationActionsOption as AutomationActionsOption,
    AbTestCreateRequestVNext as AbTestCreateRequestVNext,
    AssociationDefinitionEgg as AssociationDefinitionEgg,
    BatchInputPropertyCreate as BatchInputPropertyCreate,
    BatchInputPublicObjectID as BatchInputPublicObjectID,
    CrmObjectSnapshotRequest as CrmObjectSnapshotRequest,
    CrmObjectSnapshotResponse as CrmObjectSnapshotResponse,
    ObjectTypeDefinitionPatch as ObjectTypeDefinitionPatch,
    SubscriptionUpsertRequest as SubscriptionUpsertRequest,
    BatchReadInputPropertyName as BatchReadInputPropertyName,
    ObjectTypeDefinitionLabels as ObjectTypeDefinitionLabels,
    PropertyModificationMetadata as PropertyModificationMetadata,
    CrmObjectSnapshotBatchRequest as CrmObjectSnapshotBatchRequest,
    CrmObjectSnapshotBatchResponse as CrmObjectSnapshotBatchResponse,
    ObjectSubscriptionUpsertRequest as ObjectSubscriptionUpsertRequest,
    BatchResponseJournalFetchResponse as BatchResponseJournalFetchResponse,
    AssociationSubscriptionUpsertRequest as AssociationSubscriptionUpsertRequest,
    CollectionResponsePropertyGroupNoPaging as CollectionResponsePropertyGroupNoPaging,
    ListMembershipSubscriptionUpsertRequest as ListMembershipSubscriptionUpsertRequest,
    AppLifecycleEventSubscriptionUpsertRequest as AppLifecycleEventSubscriptionUpsertRequest,
    BatchResponseJournalFetchResponseWithErrors as BatchResponseJournalFetchResponseWithErrors,
    GdprPrivacyDeletionSubscriptionUpsertRequest as GdprPrivacyDeletionSubscriptionUpsertRequest,
)
