# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .shared import (
    Option as Option,
    Paging as Paging,
    NextPage as NextPage,
    Property as Property,
    ErrorData as ErrorData,
    ErrorDetail as ErrorDetail,
    OptionInput as OptionInput,
    TaskLocator as TaskLocator,
    VersionUser as VersionUser,
    PreviousPage as PreviousPage,
    PropertyName as PropertyName,
    ForwardPaging as ForwardPaging,
    PropertyGroup as PropertyGroup,
    PropertyValue as PropertyValue,
    StandardError as StandardError,
    ActionResponse as ActionResponse,
    PropertyCreate as PropertyCreate,
    PublicObjectID as PublicObjectID,
    AssociationSpec as AssociationSpec,
    BatchInputString as BatchInputString,
    PropertyGroupCreate as PropertyGroupCreate,
    PropertyGroupUpdate as PropertyGroupUpdate,
    ObjectTypeDefinition as ObjectTypeDefinition,
    AssociationDefinition as AssociationDefinition,
    BatchInputPropertyName as BatchInputPropertyName,
    AutomationActionsOption as AutomationActionsOption,
    AbTestCreateRequestVNext as AbTestCreateRequestVNext,
    AssociationDefinitionEgg as AssociationDefinitionEgg,
    BatchInputPropertyCreate as BatchInputPropertyCreate,
    BatchInputPublicObjectID as BatchInputPublicObjectID,
    ObjectTypeDefinitionPatch as ObjectTypeDefinitionPatch,
    BatchReadInputPropertyName as BatchReadInputPropertyName,
    ObjectTypeDefinitionLabels as ObjectTypeDefinitionLabels,
    PropertyModificationMetadata as PropertyModificationMetadata,
    CollectionResponsePropertyGroupNoPaging as CollectionResponsePropertyGroupNoPaging,
)
