# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .folder_get_params import FolderGetParams as FolderGetParams
from .folder_list_params import FolderListParams as FolderListParams
from .draft_update_params import DraftUpdateParams as DraftUpdateParams
from .folder_create_params import FolderCreateParams as FolderCreateParams
from .folder_delete_params import FolderDeleteParams as FolderDeleteParams
from .folder_update_params import FolderUpdateParams as FolderUpdateParams
from .folder_batch_get_params import FolderBatchGetParams as FolderBatchGetParams
from .folder_create_folders_params import FolderCreateFoldersParams as FolderCreateFoldersParams
from .folder_delete_folders_params import FolderDeleteFoldersParams as FolderDeleteFoldersParams
from .folder_list_revisions_params import FolderListRevisionsParams as FolderListRevisionsParams
from .folder_update_folders_params import FolderUpdateFoldersParams as FolderUpdateFoldersParams
from .batch_get_landing_pages_params import BatchGetLandingPagesParams as BatchGetLandingPagesParams
from .batch_create_landing_pages_params import BatchCreateLandingPagesParams as BatchCreateLandingPagesParams
from .batch_delete_landing_pages_params import BatchDeleteLandingPagesParams as BatchDeleteLandingPagesParams
from .batch_update_landing_pages_params import BatchUpdateLandingPagesParams as BatchUpdateLandingPagesParams
from .ab_test_end_landing_page_test_params import AbTestEndLandingPageTestParams as AbTestEndLandingPageTestParams
from .ab_test_rerun_landing_page_test_params import AbTestRerunLandingPageTestParams as AbTestRerunLandingPageTestParams
from .multi_language_update_languages_params import (
    MultiLanguageUpdateLanguagesParams as MultiLanguageUpdateLanguagesParams,
)
from .multi_language_attach_to_lang_group_params import (
    MultiLanguageAttachToLangGroupParams as MultiLanguageAttachToLangGroupParams,
)
from .multi_language_set_new_lang_primary_params import (
    MultiLanguageSetNewLangPrimaryParams as MultiLanguageSetNewLangPrimaryParams,
)
from .revision_list_landing_page_revisions_params import (
    RevisionListLandingPageRevisionsParams as RevisionListLandingPageRevisionsParams,
)
from .ab_test_create_landing_page_variation_params import (
    AbTestCreateLandingPageVariationParams as AbTestCreateLandingPageVariationParams,
)
from .multi_language_detach_from_lang_group_params import (
    MultiLanguageDetachFromLangGroupParams as MultiLanguageDetachFromLangGroupParams,
)
from .multi_language_create_language_variation_params import (
    MultiLanguageCreateLanguageVariationParams as MultiLanguageCreateLanguageVariationParams,
)
