# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from pydantic import Field as FieldInfo

from ..._models import BaseModel

__all__ = ["MetricsCounters"]


class MetricsCounters(BaseModel):
    influenced_contacts: int = FieldInfo(alias="influencedContacts")
    """The number of contacts influenced by the campaign."""

    new_contacts_first_touch: int = FieldInfo(alias="newContactsFirstTouch")
    """The number of new contacts attributed to the campaign as the first touchpoint."""

    new_contacts_last_touch: int = FieldInfo(alias="newContactsLastTouch")
    """The number of new contacts attributed to the campaign as the last touchpoint."""

    sessions: int
    """The total number of sessions generated by the campaign."""
