# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from datetime import datetime
from typing_extensions import Literal

from pydantic import Field as FieldInfo

from ..._models import BaseModel
from .public_email_content import PublicEmailContent
from .email_statistics_data import EmailStatisticsData
from .public_email_to_details import PublicEmailToDetails
from .public_rss_email_details import PublicRssEmailDetails
from .public_email_from_details import PublicEmailFromDetails
from .public_webversion_details import PublicWebversionDetails
from .public_email_testing_details import PublicEmailTestingDetails
from .public_email_subscription_details import PublicEmailSubscriptionDetails

__all__ = ["PublicEmail"]


class PublicEmail(BaseModel):
    is_ab: bool = FieldInfo(alias="isAb")

    id: Optional[str] = None
    """The email ID."""

    active_domain: Optional[str] = FieldInfo(alias="activeDomain", default=None)
    """The active domain of the email."""

    all_email_campaign_ids: Optional[List[str]] = FieldInfo(alias="allEmailCampaignIds", default=None)
    """List of emailCampaignIds."""

    archived: Optional[bool] = None
    """Determines if the email is archived or not."""

    business_unit_id: Optional[str] = FieldInfo(alias="businessUnitId", default=None)

    campaign: Optional[str] = None
    """The ID of the campaign this email is associated to."""

    campaign_name: Optional[str] = FieldInfo(alias="campaignName", default=None)
    """The name of the campaign."""

    campaign_utm: Optional[str] = FieldInfo(alias="campaignUtm", default=None)

    cloned_from: Optional[str] = FieldInfo(alias="clonedFrom", default=None)
    """The ID of the email this email was cloned from."""

    content: Optional[PublicEmailContent] = None

    created_at: Optional[datetime] = FieldInfo(alias="createdAt", default=None)
    """The date and time of the email's creation, in ISO8601 representation."""

    created_by_id: Optional[str] = FieldInfo(alias="createdById", default=None)
    """The id of the user who created the email."""

    deleted_at: Optional[datetime] = FieldInfo(alias="deletedAt", default=None)
    """The date and time the email was deleted at, in ISO8601 representation."""

    email_campaign_group_id: Optional[str] = FieldInfo(alias="emailCampaignGroupId", default=None)

    email_template_mode: Optional[Literal["DESIGN_MANAGER", "DRAG_AND_DROP"]] = FieldInfo(
        alias="emailTemplateMode", default=None
    )

    feedback_survey_id: Optional[str] = FieldInfo(alias="feedbackSurveyId", default=None)
    """The ID of the feedback survey linked to the email."""

    folder_id: Optional[int] = FieldInfo(alias="folderId", default=None)

    folder_id_v2: Optional[int] = FieldInfo(alias="folderIdV2", default=None)

    from_: Optional[PublicEmailFromDetails] = FieldInfo(alias="from", default=None)

    is_published: Optional[bool] = FieldInfo(alias="isPublished", default=None)
    """Returns the published status of the email. This is read only."""

    is_transactional: Optional[bool] = FieldInfo(alias="isTransactional", default=None)
    """Returns whether the email is a transactional email or not. This is read only."""

    jitter_send_time: Optional[bool] = FieldInfo(alias="jitterSendTime", default=None)

    language: Optional[
        Literal[
            "aa",
            "ab",
            "ae",
            "af",
            "af-na",
            "af-za",
            "agq",
            "agq-cm",
            "ak",
            "ak-gh",
            "am",
            "am-et",
            "an",
            "ann",
            "ann-ng",
            "ar",
            "ar-001",
            "ar-ae",
            "ar-bh",
            "ar-dj",
            "ar-dz",
            "ar-eg",
            "ar-eh",
            "ar-er",
            "ar-il",
            "ar-iq",
            "ar-jo",
            "ar-km",
            "ar-kw",
            "ar-lb",
            "ar-ly",
            "ar-ma",
            "ar-mr",
            "ar-om",
            "ar-ps",
            "ar-qa",
            "ar-sa",
            "ar-sd",
            "ar-so",
            "ar-ss",
            "ar-sy",
            "ar-td",
            "ar-tn",
            "ar-ye",
            "as",
            "as-in",
            "asa",
            "asa-tz",
            "ast",
            "ast-es",
            "av",
            "ay",
            "az",
            "az-az",
            "ba",
            "bal",
            "bal-pk",
            "bas",
            "bas-cm",
            "be",
            "be-by",
            "bem",
            "bem-zm",
            "bez",
            "bez-tz",
            "bg",
            "bg-bg",
            "bgc",
            "bgc-in",
            "bho",
            "bho-in",
            "bi",
            "blo",
            "blo-bj",
            "bm",
            "bm-ml",
            "bn",
            "bn-bd",
            "bn-in",
            "bo",
            "bo-cn",
            "bo-in",
            "br",
            "br-fr",
            "brx",
            "brx-in",
            "bs",
            "bs-ba",
            "ca",
            "ca-ad",
            "ca-es",
            "ca-fr",
            "ca-it",
            "ccp",
            "ccp-bd",
            "ccp-in",
            "ce",
            "ce-ru",
            "ceb",
            "ceb-ph",
            "cgg",
            "cgg-ug",
            "ch",
            "chr",
            "chr-us",
            "ckb",
            "ckb-iq",
            "ckb-ir",
            "co",
            "cr",
            "cs",
            "cs-cz",
            "csw",
            "csw-ca",
            "cu",
            "cu-ru",
            "cv",
            "cv-ru",
            "cy",
            "cy-gb",
            "da",
            "da-dk",
            "da-gl",
            "dav",
            "dav-ke",
            "de",
            "de-at",
            "de-be",
            "de-ch",
            "de-de",
            "de-gr",
            "de-it",
            "de-li",
            "de-lu",
            "dje",
            "dje-ne",
            "doi",
            "doi-in",
            "dsb",
            "dsb-de",
            "dua",
            "dua-cm",
            "dv",
            "dyo",
            "dyo-sn",
            "dz",
            "dz-bt",
            "ebu",
            "ebu-ke",
            "ee",
            "ee-gh",
            "ee-tg",
            "el",
            "el-cy",
            "el-gr",
            "en",
            "en-001",
            "en-150",
            "en-ae",
            "en-ag",
            "en-ai",
            "en-as",
            "en-at",
            "en-au",
            "en-bb",
            "en-be",
            "en-bi",
            "en-bm",
            "en-bs",
            "en-bw",
            "en-bz",
            "en-ca",
            "en-cc",
            "en-ch",
            "en-ck",
            "en-cm",
            "en-cn",
            "en-cx",
            "en-cy",
            "en-cz",
            "en-de",
            "en-dg",
            "en-dk",
            "en-dm",
            "en-ee",
            "en-eg",
            "en-er",
            "en-es",
            "en-fi",
            "en-fj",
            "en-fk",
            "en-fm",
            "en-fr",
            "en-gb",
            "en-gd",
            "en-gg",
            "en-gh",
            "en-gi",
            "en-gm",
            "en-gs",
            "en-gu",
            "en-gy",
            "en-hk",
            "en-hu",
            "en-id",
            "en-ie",
            "en-il",
            "en-im",
            "en-in",
            "en-io",
            "en-it",
            "en-je",
            "en-jm",
            "en-ke",
            "en-ki",
            "en-kn",
            "en-ky",
            "en-lc",
            "en-lr",
            "en-ls",
            "en-lu",
            "en-mg",
            "en-mh",
            "en-mo",
            "en-mp",
            "en-ms",
            "en-mt",
            "en-mu",
            "en-mv",
            "en-mw",
            "en-mx",
            "en-my",
            "en-na",
            "en-nf",
            "en-ng",
            "en-nl",
            "en-no",
            "en-nr",
            "en-nu",
            "en-nz",
            "en-pg",
            "en-ph",
            "en-pk",
            "en-pl",
            "en-pn",
            "en-pr",
            "en-pt",
            "en-pw",
            "en-ro",
            "en-rw",
            "en-sb",
            "en-sc",
            "en-sd",
            "en-se",
            "en-sg",
            "en-sh",
            "en-si",
            "en-sk",
            "en-sl",
            "en-ss",
            "en-sx",
            "en-sz",
            "en-tc",
            "en-th",
            "en-tk",
            "en-tn",
            "en-to",
            "en-tt",
            "en-tv",
            "en-tz",
            "en-ug",
            "en-um",
            "en-us",
            "en-vc",
            "en-vg",
            "en-vi",
            "en-vn",
            "en-vu",
            "en-ws",
            "en-za",
            "en-zm",
            "en-zw",
            "eo",
            "eo-001",
            "es",
            "es-419",
            "es-ar",
            "es-bo",
            "es-br",
            "es-bz",
            "es-cl",
            "es-co",
            "es-cr",
            "es-cu",
            "es-do",
            "es-ea",
            "es-ec",
            "es-es",
            "es-gq",
            "es-gt",
            "es-hn",
            "es-ic",
            "es-mx",
            "es-ni",
            "es-pa",
            "es-pe",
            "es-ph",
            "es-pr",
            "es-py",
            "es-sv",
            "es-us",
            "es-uy",
            "es-ve",
            "et",
            "et-ee",
            "eu",
            "eu-es",
            "ewo",
            "ewo-cm",
            "fa",
            "fa-af",
            "fa-ir",
            "ff",
            "ff-bf",
            "ff-cm",
            "ff-gh",
            "ff-gm",
            "ff-gn",
            "ff-gw",
            "ff-lr",
            "ff-mr",
            "ff-ne",
            "ff-ng",
            "ff-sl",
            "ff-sn",
            "fi",
            "fi-fi",
            "fil",
            "fil-ph",
            "fj",
            "fo",
            "fo-dk",
            "fo-fo",
            "fr",
            "fr-be",
            "fr-bf",
            "fr-bi",
            "fr-bj",
            "fr-bl",
            "fr-ca",
            "fr-cd",
            "fr-cf",
            "fr-cg",
            "fr-ch",
            "fr-ci",
            "fr-cm",
            "fr-dj",
            "fr-dz",
            "fr-fr",
            "fr-ga",
            "fr-gf",
            "fr-gn",
            "fr-gp",
            "fr-gq",
            "fr-ht",
            "fr-km",
            "fr-lu",
            "fr-ma",
            "fr-mc",
            "fr-mf",
            "fr-mg",
            "fr-ml",
            "fr-mq",
            "fr-mr",
            "fr-mu",
            "fr-nc",
            "fr-ne",
            "fr-pf",
            "fr-pm",
            "fr-re",
            "fr-rw",
            "fr-sc",
            "fr-sn",
            "fr-sy",
            "fr-td",
            "fr-tg",
            "fr-tn",
            "fr-vu",
            "fr-wf",
            "fr-yt",
            "frr",
            "frr-de",
            "fur",
            "fur-it",
            "fy",
            "fy-nl",
            "ga",
            "ga-gb",
            "ga-ie",
            "gaa",
            "gaa-gh",
            "gd",
            "gd-gb",
            "gl",
            "gl-es",
            "gn",
            "gsw",
            "gsw-ch",
            "gsw-fr",
            "gsw-li",
            "gu",
            "gu-in",
            "guz",
            "guz-ke",
            "gv",
            "gv-im",
            "ha",
            "ha-gh",
            "ha-ne",
            "ha-ng",
            "haw",
            "haw-us",
            "he",
            "he-il",
            "hi",
            "hi-in",
            "hmn",
            "ho",
            "hr",
            "hr-ba",
            "hr-hr",
            "hsb",
            "hsb-de",
            "ht",
            "ht-ht",
            "hu",
            "hu-hu",
            "hy",
            "hy-am",
            "hz",
            "ia",
            "ia-001",
            "id",
            "id-id",
            "ie",
            "ie-ee",
            "ig",
            "ig-ng",
            "ii",
            "ii-cn",
            "ik",
            "io",
            "is",
            "is-is",
            "it",
            "it-ch",
            "it-it",
            "it-sm",
            "it-va",
            "iu",
            "ja",
            "ja-jp",
            "jgo",
            "jgo-cm",
            "jmc",
            "jmc-tz",
            "jv",
            "jv-id",
            "ka",
            "ka-ge",
            "kab",
            "kab-dz",
            "kam",
            "kam-ke",
            "kar",
            "kde",
            "kde-tz",
            "kea",
            "kea-cv",
            "kg",
            "kgp",
            "kgp-br",
            "kh",
            "khq",
            "khq-ml",
            "ki",
            "ki-ke",
            "kj",
            "kk",
            "kk-kz",
            "kkj",
            "kkj-cm",
            "kl",
            "kl-gl",
            "kln",
            "kln-ke",
            "km",
            "km-kh",
            "kn",
            "kn-in",
            "ko",
            "ko-cn",
            "ko-kp",
            "ko-kr",
            "kok",
            "kok-in",
            "kr",
            "ks",
            "ks-in",
            "ksb",
            "ksb-tz",
            "ksf",
            "ksf-cm",
            "ksh",
            "ksh-de",
            "ku",
            "ku-tr",
            "kv",
            "kw",
            "kw-gb",
            "kxv",
            "kxv-in",
            "ky",
            "ky-kg",
            "la",
            "lag",
            "lag-tz",
            "lb",
            "lb-lu",
            "lg",
            "lg-ug",
            "li",
            "lij",
            "lij-it",
            "lkt",
            "lkt-us",
            "lmo",
            "lmo-it",
            "ln",
            "ln-ao",
            "ln-cd",
            "ln-cf",
            "ln-cg",
            "lo",
            "lo-la",
            "lrc",
            "lrc-iq",
            "lrc-ir",
            "lt",
            "lt-lt",
            "lu",
            "lu-cd",
            "luo",
            "luo-ke",
            "luy",
            "luy-ke",
            "lv",
            "lv-lv",
            "mai",
            "mai-in",
            "mas",
            "mas-ke",
            "mas-tz",
            "mdf",
            "mdf-ru",
            "mer",
            "mer-ke",
            "mfe",
            "mfe-mu",
            "mg",
            "mg-mg",
            "mgh",
            "mgh-mz",
            "mgo",
            "mgo-cm",
            "mh",
            "mi",
            "mi-nz",
            "mk",
            "mk-mk",
            "ml",
            "ml-in",
            "mn",
            "mn-mn",
            "mni",
            "mni-in",
            "mr",
            "mr-in",
            "ms",
            "ms-bn",
            "ms-id",
            "ms-my",
            "ms-sg",
            "mt",
            "mt-mt",
            "mua",
            "mua-cm",
            "my",
            "my-mm",
            "mzn",
            "mzn-ir",
            "na",
            "naq",
            "naq-na",
            "nb",
            "nb-no",
            "nb-sj",
            "nd",
            "nd-zw",
            "nds",
            "nds-de",
            "nds-nl",
            "ne",
            "ne-in",
            "ne-np",
            "ng",
            "nl",
            "nl-aw",
            "nl-be",
            "nl-bq",
            "nl-ch",
            "nl-cw",
            "nl-lu",
            "nl-nl",
            "nl-sr",
            "nl-sx",
            "nmg",
            "nmg-cm",
            "nn",
            "nn-no",
            "nnh",
            "nnh-cm",
            "no",
            "no-no",
            "nqo",
            "nqo-gn",
            "nr",
            "nso",
            "nso-za",
            "nus",
            "nus-ss",
            "nv",
            "ny",
            "nyn",
            "nyn-ug",
            "oc",
            "oc-es",
            "oc-fr",
            "oj",
            "om",
            "om-et",
            "om-ke",
            "or",
            "or-in",
            "os",
            "os-ge",
            "os-ru",
            "pa",
            "pa-in",
            "pa-pk",
            "pcm",
            "pcm-ng",
            "pi",
            "pis",
            "pis-sb",
            "pl",
            "pl-pl",
            "prg",
            "prg-001",
            "ps",
            "ps-af",
            "ps-pk",
            "pt",
            "pt-ao",
            "pt-br",
            "pt-ch",
            "pt-cv",
            "pt-gq",
            "pt-gw",
            "pt-lu",
            "pt-mo",
            "pt-mz",
            "pt-pt",
            "pt-st",
            "pt-tl",
            "qu",
            "qu-bo",
            "qu-ec",
            "qu-pe",
            "raj",
            "raj-in",
            "rm",
            "rm-ch",
            "rn",
            "rn-bi",
            "ro",
            "ro-md",
            "ro-ro",
            "rof",
            "rof-tz",
            "ru",
            "ru-by",
            "ru-kg",
            "ru-kz",
            "ru-md",
            "ru-ru",
            "ru-ua",
            "rw",
            "rw-rw",
            "rwk",
            "rwk-tz",
            "sa",
            "sa-in",
            "sah",
            "sah-ru",
            "saq",
            "saq-ke",
            "sat",
            "sat-in",
            "sbp",
            "sbp-tz",
            "sc",
            "sc-it",
            "sd",
            "sd-in",
            "sd-pk",
            "se",
            "se-fi",
            "se-no",
            "se-se",
            "seh",
            "seh-mz",
            "ses",
            "ses-ml",
            "sg",
            "sg-cf",
            "shi",
            "shi-ma",
            "si",
            "si-lk",
            "sk",
            "sk-sk",
            "sl",
            "sl-si",
            "sm",
            "smn",
            "smn-fi",
            "sms",
            "sms-fi",
            "sn",
            "sn-zw",
            "so",
            "so-dj",
            "so-et",
            "so-ke",
            "so-so",
            "sq",
            "sq-al",
            "sq-mk",
            "sq-xk",
            "sr",
            "sr-ba",
            "sr-cs",
            "sr-me",
            "sr-rs",
            "sr-xk",
            "ss",
            "st",
            "st-ls",
            "st-za",
            "su",
            "su-id",
            "sv",
            "sv-ax",
            "sv-fi",
            "sv-se",
            "sw",
            "sw-cd",
            "sw-ke",
            "sw-tz",
            "sw-ug",
            "sy",
            "syr",
            "syr-iq",
            "syr-sy",
            "szl",
            "szl-pl",
            "ta",
            "ta-in",
            "ta-lk",
            "ta-my",
            "ta-sg",
            "te",
            "te-in",
            "teo",
            "teo-ke",
            "teo-ug",
            "tg",
            "tg-tj",
            "th",
            "th-th",
            "ti",
            "ti-er",
            "ti-et",
            "tk",
            "tk-tm",
            "tl",
            "tn",
            "tn-bw",
            "tn-za",
            "to",
            "to-to",
            "tok",
            "tok-001",
            "tr",
            "tr-cy",
            "tr-tr",
            "ts",
            "tt",
            "tt-ru",
            "tw",
            "twq",
            "twq-ne",
            "ty",
            "tzm",
            "tzm-ma",
            "ug",
            "ug-cn",
            "uk",
            "uk-ua",
            "ur",
            "ur-in",
            "ur-pk",
            "uz",
            "uz-af",
            "uz-uz",
            "vai",
            "vai-lr",
            "ve",
            "vec",
            "vec-it",
            "vi",
            "vi-vn",
            "vmw",
            "vmw-mz",
            "vo",
            "vo-001",
            "vun",
            "vun-tz",
            "wa",
            "wae",
            "wae-ch",
            "wo",
            "wo-sn",
            "xh",
            "xh-za",
            "xnr",
            "xnr-in",
            "xog",
            "xog-ug",
            "yav",
            "yav-cm",
            "yi",
            "yi-001",
            "yi-ua",
            "yo",
            "yo-bj",
            "yo-ng",
            "yrl",
            "yrl-br",
            "yrl-co",
            "yrl-ve",
            "yue",
            "yue-cn",
            "yue-hk",
            "yue-mo",
            "za",
            "za-cn",
            "zgh",
            "zgh-ma",
            "zh",
            "zh-cn",
            "zh-hans",
            "zh-hant",
            "zh-hk",
            "zh-mo",
            "zh-my",
            "zh-sg",
            "zh-tw",
            "zu",
            "zu-za",
        ]
    ] = None

    name: Optional[str] = None
    """The name of the email, as displayed on the email dashboard."""

    preview_key: Optional[str] = FieldInfo(alias="previewKey", default=None)

    primary_email_campaign_id: Optional[str] = FieldInfo(alias="primaryEmailCampaignId", default=None)

    publish_date: Optional[datetime] = FieldInfo(alias="publishDate", default=None)
    """The date and time the email is scheduled for, in ISO8601 representation.

    This is only used in local time or scheduled emails.
    """

    published_at: Optional[datetime] = FieldInfo(alias="publishedAt", default=None)
    """The date and time the email was published at, in ISO8601 representation."""

    published_by_email: Optional[str] = FieldInfo(alias="publishedByEmail", default=None)
    """Email of the user who published/sent the email."""

    published_by_id: Optional[str] = FieldInfo(alias="publishedById", default=None)
    """The ID of the user who published the email."""

    published_by_name: Optional[str] = FieldInfo(alias="publishedByName", default=None)
    """Name of the user who published the email."""

    rss_data: Optional[PublicRssEmailDetails] = FieldInfo(alias="rssData", default=None)

    send_on_publish: Optional[bool] = FieldInfo(alias="sendOnPublish", default=None)
    """Determines whether the email will be sent immediately on publish."""

    state: Optional[
        Literal[
            "AGENT_GENERATED",
            "AUTOMATED",
            "AUTOMATED_AB",
            "AUTOMATED_AB_VARIANT",
            "AUTOMATED_DRAFT",
            "AUTOMATED_DRAFT_AB",
            "AUTOMATED_DRAFT_ABVARIANT",
            "AUTOMATED_FOR_FORM",
            "AUTOMATED_FOR_FORM_BUFFER",
            "AUTOMATED_FOR_FORM_DRAFT",
            "AUTOMATED_FOR_FORM_LEGACY",
            "AUTOMATED_LOSER_ABVARIANT",
            "AUTOMATED_SENDING",
            "BLOG_EMAIL_DRAFT",
            "BLOG_EMAIL_PUBLISHED",
            "DRAFT",
            "DRAFT_AB",
            "DRAFT_AB_VARIANT",
            "ERROR",
            "LOSER_AB_VARIANT",
            "PAGE_STUB",
            "PRE_PROCESSING",
            "PROCESSING",
            "PUBLISHED",
            "PUBLISHED_AB",
            "PUBLISHED_AB_VARIANT",
            "PUBLISHED_OR_SCHEDULED",
            "RSS_TO_EMAIL_DRAFT",
            "RSS_TO_EMAIL_PUBLISHED",
            "SCHEDULED",
            "SCHEDULED_AB",
            "SCHEDULED_OR_PUBLISHED",
        ]
    ] = None
    """The email state."""

    stats: Optional[EmailStatisticsData] = None

    subcategory: Optional[str] = None
    """The email subcategory."""

    subject: Optional[str] = None
    """The subject of the email."""

    subscription_details: Optional[PublicEmailSubscriptionDetails] = FieldInfo(
        alias="subscriptionDetails", default=None
    )

    teams_with_access: Optional[List[str]] = FieldInfo(alias="teamsWithAccess", default=None)

    testing: Optional[PublicEmailTestingDetails] = None

    to: Optional[PublicEmailToDetails] = None

    type: Optional[
        Literal[
            "AB_EMAIL",
            "AUTOMATED_AB_EMAIL",
            "AUTOMATED_EMAIL",
            "BATCH_EMAIL",
            "BLOG_EMAIL",
            "BLOG_EMAIL_CHILD",
            "FEEDBACK_CES_EMAIL",
            "FEEDBACK_CUSTOM_EMAIL",
            "FEEDBACK_CUSTOM_SURVEY_EMAIL",
            "FEEDBACK_NPS_EMAIL",
            "FOLLOWUP_EMAIL",
            "LEADFLOW_EMAIL",
            "LOCALTIME_EMAIL",
            "MANAGE_PREFERENCES_EMAIL",
            "MARKETING_SINGLE_SEND_API",
            "MEMBERSHIP_EMAIL_VERIFICATION_EMAIL",
            "MEMBERSHIP_FOLLOW_UP_EMAIL",
            "MEMBERSHIP_OTP_LOGIN_EMAIL",
            "MEMBERSHIP_PASSWORD_RESET_EMAIL",
            "MEMBERSHIP_PASSWORD_SAVED_EMAIL",
            "MEMBERSHIP_PASSWORDLESS_AUTH_EMAIL",
            "MEMBERSHIP_REGISTRATION_EMAIL",
            "MEMBERSHIP_REGISTRATION_FOLLOW_UP_EMAIL",
            "MEMBERSHIP_VERIFICATION_EMAIL",
            "OPTIN_EMAIL",
            "OPTIN_FOLLOWUP_EMAIL",
            "RESUBSCRIBE_EMAIL",
            "RSS_EMAIL",
            "RSS_EMAIL_CHILD",
            "SINGLE_SEND_API",
            "SMTP_TOKEN",
            "TICKET_EMAIL",
        ]
    ] = None
    """
    The email type, this is derived from other properties on the email such as
    subcategory.
    """

    unpublished_at: Optional[datetime] = FieldInfo(alias="unpublishedAt", default=None)

    updated_at: Optional[datetime] = FieldInfo(alias="updatedAt", default=None)
    """The date and time of the last update to the email, in ISO8601 representation."""

    updated_by_id: Optional[str] = FieldInfo(alias="updatedById", default=None)
    """The id of the user who last updated the email."""

    users_with_access: Optional[List[str]] = FieldInfo(alias="usersWithAccess", default=None)

    webversion: Optional[PublicWebversionDetails] = None

    workflow_names: Optional[List[str]] = FieldInfo(alias="workflowNames", default=None)
    """Names of workflows in which the email is used within a "send email" action."""
